language: node_js
node_js:
  - "10.18.0"

before_install:
  - export TZ='Asia/Shanghai'

install:
  - npm install lerna -g
  - npm install
  - npm run start
  - cd site

script:
  - node ../packages/mdppt build mdppt.md

after_script:
  - cd ../dist
  - echo 'mdppt.loadingmore.com' > CNAME
  - git init
  - git config user.name "BiYuqi"
  - git config user.email "biyuqiwan@163.com"
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://${MDPPT}@${GH_REF}" master:gh-pages

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/ftbjs/mdppt.git
